/**
 * xq-004: writes src/features/board/glyphs.ts, the outlines of the piece characters and the river text,
 * so the board never needs a CJK font (owner decision D4 and D9).
 *
 * Usage: npm run glyphs -w apps/xiangqi/web   (needs network; the output is committed)
 *
 * The outlines come from Noto Serif TC Black (SIL Open Font License 1.1, see src/features/board/OFL.txt),
 * fetched as a subset of exactly these characters from Google Fonts. Each glyph is centred in a 100x100 box.
 */
import { writeFileSync } from 'node:fs';
import opentype from 'opentype.js';

const PIECES = {
  w: { k: '帥', a: '仕', b: '相', n: '傌', r: '俥', c: '炮', p: '兵' },
  b: { k: '將', a: '士', b: '象', n: '馬', r: '車', c: '砲', p: '卒' },
};
const RIVER = '楚河漢界';
const FAMILY = 'Noto+Serif+TC:wght@900';
const GLYPH_SIZE = 58;

const text = [...Object.values(PIECES.w), ...Object.values(PIECES.b), ...RIVER].join('');
// An old user agent makes Google Fonts serve TrueType, which opentype.js reads (it does not read WOFF2).
const css = await (
  await fetch(`https://fonts.googleapis.com/css2?family=${FAMILY}&text=${encodeURIComponent(text)}`, {
    headers: { 'User-Agent': 'Mozilla/4.0' },
  })
).text();
const fontUrl = css.match(/url\((https:[^)]+)\)/)?.[1];
if (!fontUrl) throw new Error(`No font URL in:\n${css}`);
const font = opentype.parse(await (await fetch(fontUrl)).arrayBuffer());

function centred(ch) {
  const box = font.getPath(ch, 0, 0, GLYPH_SIZE).getBoundingBox();
  return font.getPath(ch, 50 - (box.x1 + box.x2) / 2, 50 - (box.y1 + box.y2) / 2, GLYPH_SIZE).toPathData(1);
}

const pieces = Object.fromEntries(
  Object.entries(PIECES).map(([color, types]) => [
    color,
    Object.fromEntries(Object.entries(types).map(([type, ch]) => [type, { char: ch, d: centred(ch) }])),
  ]),
);
const river = Object.fromEntries([...RIVER].map((ch) => [ch, centred(ch)]));

writeFileSync(
  new URL('../src/features/board/glyphs.ts', import.meta.url),
  `/**
 * Generated by scripts/generate-glyphs.mjs: do not edit. Outlines of Noto Serif TC Black (SIL Open Font
 * License 1.1, see OFL.txt next to this file), each centred in a 100x100 box.
 */
export const PIECE_GLYPHS = ${JSON.stringify(pieces, null, 2)} as const;

/** The river text, one character per entry, in reading order. */
export const RIVER_GLYPHS = ${JSON.stringify(river, null, 2)} as const;
`,
);
console.log('wrote src/features/board/glyphs.ts');
