/**
 * sg-004: writes src/features/board/glyphs.ts, the outlines of the piece kanji, so the board never needs a
 * Japanese font (owner decisions D4 and D9).
 *
 * Usage: npm run glyphs -w apps/shogi/web   (needs network; the output is committed)
 *
 * The outlines come from Noto Serif JP Black (SIL Open Font License 1.1, see src/features/board/OFL.txt),
 * fetched as a subset of exactly these characters from Google Fonts. Each glyph is centred in a 100x100 box.
 *
 * Both players use the same faces — a Shogi piece belongs to whoever it points at — so there is one glyph
 * per piece, plus the promoted face, which is written in red on a real set.
 */
import { writeFileSync } from 'node:fs';
import opentype from 'opentype.js';

/** The face of each piece, and the face it shows once promoted. */
const PIECES = {
  k: { char: '王', promoted: null },
  r: { char: '飛', promoted: '龍' },
  b: { char: '角', promoted: '馬' },
  g: { char: '金', promoted: null },
  s: { char: '銀', promoted: '全' },
  n: { char: '桂', promoted: '圭' },
  l: { char: '香', promoted: '杏' },
  p: { char: '歩', promoted: 'と' },
};
/** Gote's king carries the other character of the pair (玉将), as on a real set. */
const GOTE_KING = '玉';
const FAMILY = 'Noto+Serif+JP:wght@900';
const GLYPH_SIZE = 56;

const text = [...Object.values(PIECES).flatMap((p) => [p.char, p.promoted]).filter(Boolean), GOTE_KING].join('');
// An old user agent makes Google Fonts serve TrueType, which opentype.js reads (it does not read WOFF2).
const css = await (
  await fetch(`https://fonts.googleapis.com/css2?family=${FAMILY}&text=${encodeURIComponent(text)}`, {
    headers: { 'User-Agent': 'Mozilla/4.0' },
  })
).text();
const fontUrl = css.match(/url\((https:[^)]+)\)/)?.[1];
if (!fontUrl) throw new Error(`No font URL in:\n${css}`);
const font = opentype.parse(await (await fetch(fontUrl)).arrayBuffer());

function centred(ch) {
  const box = font.getPath(ch, 0, 0, GLYPH_SIZE).getBoundingBox();
  return font.getPath(ch, 50 - (box.x1 + box.x2) / 2, 50 - (box.y1 + box.y2) / 2, GLYPH_SIZE).toPathData(1);
}

const glyph = (ch) => ({ char: ch, d: centred(ch) });
const pieces = Object.fromEntries(
  Object.entries(PIECES).map(([type, { char, promoted }]) => [
    type,
    { plain: glyph(char), promoted: promoted ? glyph(promoted) : null },
  ]),
);

writeFileSync(
  new URL('../src/features/board/glyphs.ts', import.meta.url),
  `/**
 * Generated by scripts/generate-glyphs.mjs: do not edit. Outlines of Noto Serif JP Black (SIL Open Font
 * License 1.1, see OFL.txt next to this file), each centred in a 100x100 box.
 */
export const PIECE_GLYPHS = ${JSON.stringify(pieces, null, 2)} as const;

/** Gote's king shows the other character of the pair, as on a real set. */
export const GOTE_KING_GLYPH = ${JSON.stringify(glyph(GOTE_KING), null, 2)} as const;
`,
);
console.log('wrote src/features/board/glyphs.ts');
